# Generated by Django 4.0.1 on 2022-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrysendingtravelagency',
            name='account_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Номер счета'),
        ),
    ]
