# Generated by Django 4.0.1 on 2022-01-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color_group',
            field=models.CharField(choices=[('red', 'Красный'), ('blue', 'Синий'), ('orange', 'Оранжевый'), ('black', 'Черный'), ('green', 'Зеленый')], default='green', max_length=6, verbose_name='Цвет выделения'),
        ),
    ]
